### ISSUE TITLE
Allow select-expression with an empty selector

### ISSUE THREAD

**Issue by stasm** [projectfluent/syntax#5]
#### Goal
Define variants of a message which can be accessed from other strings.

#### Description
We currently define variants of the message which are local and specific to the natural language using traits. For instance, we'd write:

```
brand-name =
   *[nominative] Firefox
    [genitive]    Firefox's
```

This is a bit weird because in the above example, "Firefox" is the real value of the message and nominative and genitive are the value's facets.  However the `value` field of the message remains empty due to the fact that the facets are defined as traits.  These traits also need to remain private which in turn necessitates a way to mark public traits as public; we currently use namespaces for this purpose.

The proposed change is to allow defining facets of a value as variants of a `select-expression` which doesn't have a selector:

```
brand-name = {
   *[nominative] Firefox
    [genitive]    Firefox's
}
```

This would also allow to remove namespaces from member keys (keywords).  The `member-expression` would change the meaning: it would now be used to access a named variant of the first placeable in the value of the message. If that placeable isn't a `select-expression` or already has a selector, normal evaluation would follow.

```
about1 = About { brand-name }
about2 = About { brand-name[nominative] }
```

#### Dependencies
#1.

#### Discussion
https://groups.google.com/forum/#!topic/mozilla.tools.l10n/dhWfBXHzuZI

**Comment by Pike** [comment]
I'm looking at this from the POV of a developer writing an ftl file in an editor, and from that view, it just looks as if we added two characters that I can get wrong.

I'd love to look at this proposal once we know what ot do with #6 and #7, and look at the impact then.

**Comment by stasm** [comment]
@Pike, I'd argue that from the POV of a developer this change is about putting the value into the _value_ field instead of abusing traits. And with #6 it should be clear that attributes are just that: attributes.
