### ISSUE TITLE
Disallow whitespace around member keys

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/syntax#9]
I'd like to suggest tightening a bit how we handle whitespace in member keys.

Currently this is allowed:

```rust
key =
  [ foo     ] Value
```

I propose that:

1. Member keys cannot have leading and trailing whitespaces

**Comment by stasm** [comment]
Would this apply to `member-key` or `keyword` in general? The latter is also used in section names.

**Comment by zbraniecki** [comment]
I'm ok with section names with leading/trailing whitespaces:

```rust
[[   New York   ]]
```

and the parser will trim on both ends.

**Comment by Pike** [comment]
The original description here doesn't list which problem we'd be solving here.

I'd not want to do this if it just meant that it's harder to write an ftl file that works.

There's the "be strict in what you send, be lenient in what you accept" punch line that I heard way back when.

**Comment by GlenDC** [comment]
This does seem like it makes it harder to write an FTL file by hand, without really giving much benefits. With white spaces I would stay as lenient as possible.

**Comment by stasm** [comment]
The current grammar already forbids whitespace around the `member-key` symbol:

    member               ::= __ '*'? '[' member-key ']' __ pattern NL;
    member-key ::= number | (identifier '/')? keyword;

Given @Pike's and @GlenDC's comments, perhaps we should actually allow non-new-line whitespace here?  Something like the following should do the trick:

    member               ::= __ '*'? '[' __ member-key __ ']' __ pattern NL;
    member-key ::= number | (identifier '/')? keyword;

**Comment by zbraniecki** [comment]
So, I'm still torn on this.

> This does seem like it makes it harder to write an FTL file by hand

I feel like this is a catch-all argument. Everything is easier if we allow everything :)

What exactly is so crucial in ability to add random white-spaces around member keys? Does it increase readability? Does it look cleaner?

Most whitespaces we allow serve one of those two purposes. For example:

```
# Comment
```

is more readable than:

```
#Comment
```

And
```
key         = Value
longKey = Value 2
```

is more readable than

```
key = value
longKey = Valee
```

But I'm not sure if I've ever seen a convention like:

```
key = 
  [member        ] Foo
  [longMember ] Foo
```

especially that you can do:

```
key = 
  [member]        Foo
  [longMember] Foo
```

and I believe it actually impacts the pattern matching:

```
key = 
  [member        ] Foo
  [longMember ] Foo

key2 = { key[member] }
key3 = { key[member     ] }
```

**Comment by Pike** [comment]
@zbraniecki but which problem do we solve here?

**Comment by zbraniecki** [comment]
@Pike - I believe we solve the following problems:

- we reduce the ambiguity around how white-space around member keys should be treated
- we bring consistency to how member key definition and member expression work
- we remove edge cases around white-space trimming from parsers [*]


[*] On this topic, the current behavior requires an interesting and non-trivial operation:

```rust
key =
  [foo     bar      bla         } Value


key2 =
  [foo     bar      bla         a Value

```

In the current world, the parser has to get to `}` character to recognize that there's a parser error. But he end of the member key is `a`, so it's the only place in the spec, where there is a distance between where the end of the token happened and where the error happened.
I fail to see all potential consequences of that to the edge cases.

**Comment by stasm** [comment]
(I'm going to use `_` to mark whitespace in this comment.)

> we reduce the ambiguity around how white-space around member keys should be treated

I see how this would reduce the ambiguity but I'm concerned about introducing inconsistency:

 - with sections, where the name of the section is trimmed to `foo bar`:

       [[___foo bar___]]

 - with unquoted values, where the value is left-trimmed to `foo bar___` (btw. should it be trimmed on both sides?)

       foo =___foo bar___

> we bring consistency to how member key definition and member expression work

Arguably the consistency can be introduced also by making the member expression accept whitespace: `brand-name[___nominative___]`. This sounds like an approach that is widely used by other languages.

> we remove edge cases around white-space trimming from parsers
> it's the only place in the spec, where there is a distance between where the end of the token happened and where the error happened.

I don't know about this. Doesn't every place in the grammar where whitespace is allowed have the same problem? The message is defined as:

    message ::= identifier __ '=' __ (pattern | pattern member-list | member-list);

If I make a syntax error like so, using `:` in lieu of `=`:

    foo      : Foo Value

…there too is some distance between the end of the `identifier` and the place where the error happened.

* * *

I think that i general we should be as lenient with whitespace as possible, as long as it makes our value parsing rules understandable for the user.

That said, given that the current EBNF already forbids white-space in member keys, a potential path forward is to keep the grammar more strict right now and relax it in a future milestone. It would be a fully backward-compatible change. We already have a lot in 0.2, tbh.

**Comment by stasm** [comment]
I'm going to move this to the 0.3 milestone which is mostly about making our white-space story well-defined.

**Comment by stasm** [comment]
To avoid confusion which re-purposing this issue would cause, I filed #30 to relax the syntax of the variant keys.
